# This is a basic workflow to help you get started with Actions

name: FileShare

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

env:
  AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  host:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
         python-version: 3.8 #install the python needed

      - name: setup and run 
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          ./ngrok authtoken ${AUTHTOKEN}
          ./ngrok http 8080 &
          pip install browsepy
          timeout 20m browsepy 0.0.0.0 8080 --directory . --upload .
            
