# This is a basic workflow to help you get started with Actions

name: remote-code-execution-environment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install global deps
        run: |
          sudo apt install nodejs
          sudo apt install npm
          sudo npm install npm -g
          sudo npm install -g yarn
          
      - name: clone paulonteri/remote-code-execution-environment
        run: |
          git clone https://github.com/paulonteri/remote-code-execution-environment.git --depth=1
          cd remote-code-execution-environment
          cd core && yarn install && cd ../frontend && yarn install && cd ..
      
      - name: run 
        run: ./run
      
