name: Speedtest

on:
  workflow_dispatch:
    # manual

jobs:
  execute:
    name: run
    runs-on: ubuntu-latest
    steps:

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install speedtest-cli
    - name: Run test
      run: |
        speedtest-cli --share
